### ISSUE TITLE
Scopes not working

### ISSUE THREAD

**Issue by intersimone999** [intersimone999/qtws#2]
Scopes are not working at the moment. For example, it is possible to open YouTube from the Google Photos app. The expected behavior is that the link is opened in the default browser.

**Comment by FadeMind** [comment]
I made radiobox app (http://onlineradiobox.com) When I click on Facebook or Google login in app nothing happen, seems scopes did not works.

**Comment by intersimone999** [comment]
Good point. There should be a field like "externalServices" that indicates the external services allowed in the app. Anyway, at the moment this doesn't work mainly because it doesn't handle new windows (issue #3).
